language: node_js
node_js: "14.17.4"
yarn: "1.22.11"

cache:
    yarn: true

  # whitelist
branches:
  only:
    - master
before_install:
  - git checkout master
script: 
    - yarn package --linux
after_success:
    - ls release
    - sh scripts/push.sh
env:
  global:
    - secure: RwA77HdeVP7a6O8OGVXHK7QGCKf1ZkkbOx9sNH5UH7qCl208XgDzi+EmY76YXO55HUPIWo2mj7duAkPyHybV2wB43YW2zy1WXIHzh77Z339gzhw7atEIoN0Zkau2QMOO0OY3jDlLy7cZIb6EgrYR1CuPQxbXPCkIaklmhcnq42m77fFsRzn3xIdLUIXPfnbgdu21vk1PR4LiFLFss6RuXnQGNiSmHgV+TVIQK9Iuf+6xoBqL/Ef3gGZR2ZOb8aDvKGLTgRbMqywTru1glYIaHwkOWML+lKZMNFWOwYd4JxxtRoc5Yav70xsrDhOOBjbX7OAMbPTH9hPGqVEYP16Kh2f0LQxL1XVDzcF7Ya7LbWxVKV/ZB4hvxEN7WkVyAzKtd6RCK+GPK2JTKVsDLTagclHm+nHogadxF+zTS0/w6ssJrFprkUyzvxQ74CKp2Gjl2IX8rsrxOlQNu4qUFB5U+HaId94H/TBULrUG3Y+6uzMnohyWtjE2sHxioHKqgGcqKdJGoIAvhjUoqzolPtcmjV4dFvLkOlR1V+Q5NewJ3QA7Z/FVJnfrTiXkRJ79RrXfXzcse+H+z+6hcmxrYRmMjE+OKhD+eP3tS5MJWskt30jvRFhNk6KSWcQVMSgnCxY9DAbBLy20gow1rpDXhn+F9wqIKtvjriR98e4ZqiY3qac=